# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        UserBundle\Entity\User: sha512

    role_hierarchy:
        
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            switch_user: { role: ROLE_ADMIN }
            form_login:
                provider:           fos_userbundle
                login_path:         fos_user_security_login
                check_path:         fos_user_security_check
                failure_path:       null
                use_forward:        false
                csrf_provider:      form.csrf_provider
                default_target_path: /
                remember_me:        true
            remember_me: 
                key:      %secret%
                lifetime: 30
                path:     /logout
                domain:  ~
            logout:
                path: /logout
                target: /connexion            
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: /, role: IS_AUTHENTICATED_FULLY }
        